trigger:
  branches:
    include:
      - main

stages:
  - stage: TerraformInit
    displayName: "Terraform Init"
    jobs:
      - job: init
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self

          - task: TerraformInstaller@1
            displayName: "Install Terraform"
            inputs:
              terraformVersion: '1.7.5'

          - task: AzureCLI@2
            displayName: "Terraform Init"
            inputs:
              azureSubscription: 'idaug25'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                terraform init

  - stage: TerraformPlan
    displayName: "Terraform Plan"
    dependsOn: TerraformInit
    jobs:
      - job: plan
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self

          - task: TerraformInstaller@1
            inputs:
              terraformVersion: '1.7.5'

          - task: AzureCLI@2
            displayName: "Terraform Plan"
            inputs:
              azureSubscription: 'idaug25'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                terraform validate
                terraform plan -out=tfplan

          - publish: $(System.DefaultWorkingDirectory)/tfplan
            artifact: terraformPlan

  - stage: TerraformApply
    displayName: "Terraform Apply"
    dependsOn: TerraformPlan
    condition: succeeded()
    jobs:
      - deployment: applyInfra
        environment: dev
        pool:
          vmImage: 'ubuntu-latest'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - task: TerraformInstaller@1
                  inputs:
                    terraformVersion: '1.7.5'

                - download: current
                  artifact: terraformPlan

                - task: AzureCLI@2
                  displayName: "Terraform Apply"
                  inputs:
                    azureSubscription: 'idaug25'
                    scriptType: 'bash'
                    scriptLocation: 'inlineScript'
                    inlineScript: |
                      terraform apply -auto-approve tfplan
