trigger:
  branches:
    include:
      - main

stages:
  - stage: TerraformInit
    displayName: "Terraform Init"
    jobs:
      - job: init
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'idaug25'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                cd infra
                terraform init

  - stage: TerraformPlan
    displayName: "Terraform Plan"
    dependsOn: TerraformInit
    jobs:
      - job: plan
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'idaug25'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                cd infra
                terraform validate
                terraform plan -out=tfplan

          - publish: $(System.DefaultWorkingDirectory)/infra/tfplan
            artifact: terraformPlan

  - stage: TerraformApply
    displayName: "Terraform Apply"
    dependsOn: TerraformPlan
    condition: succeeded()
    jobs:
      - deployment: applyInfra
        environment: dev
        pool:
          vmImage: 'ubuntu-latest'
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: terraformPlan

                - task: AzureCLI@2
                  inputs:
                    azureSubscription: 'idaug25'
                    scriptType: 'bash'
                    scriptLocation: 'inlineScript'
                    inlineScript: |
                      cd infra
                      terraform apply -auto-approve tfplan
